apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: member-mgmt-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: member-mgmt
    spec:
      containers:
      - name: aaspire-member-mgmt
        #use image from dockerhub for local execution
        image: manglu/membermgmt:0.8.1
        #use the image in Bluemix registry for execution in IBM Container services
        #image: manglu/membermgmt:0.8.1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aaspire-member-mgmt-service
  labels:
    app: aaspire-member-mgmt-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: member-mgmt
    