INSERT INTO ADDRESS("ID","COUNTRY","LINE1","LINE2","POST_CODE", "STATE", "SUBURB") VALUES('101','Australia', '60 City Road','Southgate', '3006', 'VIC', 'South Bank');
INSERT INTO ADDRESS("ID","COUNTRY","LINE1","LINE2","POST_CODE", "STATE", "SUBURB") VALUES('102','Australia', '50 City Road','Southgate', '3006', 'VIC', 'South Bank');
INSERT INTO ADDRESS("ID","COUNTRY","LINE1","LINE2","POST_CODE", "STATE", "SUBURB") VALUES('103','Australia', '40 City Road','Southgate', '3006', 'VIC', 'South Bank');
INSERT INTO ADDRESS("ID","COUNTRY","LINE1","LINE2","POST_CODE", "STATE", "SUBURB") VALUES('104','Australia', 'Langham Hotel','Southgate', '3006', 'VIC', 'South Bank');

INSERT INTO MEMBER ("ID","DATA_OF_BIRTH","EMAIL","GIVEN_NAME","PHONE_NUMBER","STATUS","SURNAME","TITLE","ADDRESS_ID") VALUES ('201', '1991-01-01','abc@gmail.com','Roger','12345678','ACTIVE','Federer','Mr','101');
INSERT INTO MEMBER ("ID","DATA_OF_BIRTH","EMAIL","GIVEN_NAME","PHONE_NUMBER","STATUS","SURNAME","TITLE","ADDRESS_ID") VALUES ('202', '1991-01-01','abc@gmail.com','Novak','12345678','ACTIVE','Djokovic','Mr','102');
INSERT INTO MEMBER ("ID","DATA_OF_BIRTH","EMAIL","GIVEN_NAME","PHONE_NUMBER","STATUS","SURNAME","TITLE","ADDRESS_ID") VALUES ('203', '1991-01-01','abc@gmail.com','Rafael','12345678','ACTIVE','Nadal','Mr','103');
INSERT INTO MEMBER ("ID","DATA_OF_BIRTH","EMAIL","GIVEN_NAME","PHONE_NUMBER","STATUS","SURNAME","TITLE","ADDRESS_ID") VALUES ('204', '1991-01-01','abc@gmail.com','Grigor','12345678','ACTIVE','Dimitrov','Mr','104');
INSERT INTO MEMBER ("ID","DATA_OF_BIRTH","EMAIL","GIVEN_NAME","PHONE_NUMBER","STATUS","SURNAME","TITLE","ADDRESS_ID") VALUES ('205', '1991-01-01','abc@gmail.com','Maria','12345678','ACTIVE','Sharapova','Ms','104');





